# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
        
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build the Docker image
#         run: |
#           docker build -t 220103141/flask-app:latest .

#       - name: Push Docker image to Docker Hub
#         run: |
#           docker push 220103141/flask-app:latest

#       - name: Deploy to AWS EC2
#         uses: appleboy/scp-action@v0.1.4
#         with:
#           host: ${{ secrets.AWS_EC2_HOST }}
#           username: ${{ secrets.AWS_EC2_USERNAME }}
#           key: ${{ secrets.AWS_PRIVATE_KEY }}
#           source: "docker-compose.yml"
#           target: "/home/ubuntu"

#       - name: Run Docker container on EC2
#         uses: appleboy/ssh-action@v0.1.4
#         with:
#           host: ${{ secrets.AWS_EC2_HOST }}
#           username: ${{ secrets.AWS_EC2_USERNAME }}
#           key: ${{ secrets.AWS_PRIVATE_KEY }}
#           script: |
#             docker stop flask-app || true
#             docker rm flask-app || true
#             docker pull 220103141/flask-app:latest
#             docker run -d -p 5000:5000 --name flask-app 220103141/flask-app:latest